对输出区域进行trim
halo-dev/console pull request #572
Opened 2022-05-20 08:52 UTC by FanZeros

#### What type of PR is this?
/kind bug
/kind optimization

#### What this PR does / why we need it:
对admin的部分input区域进行trim，包括地址、前缀等
避免输入部分的前后空格导致页面出错
#### Which issue(s) this PR fixes:
Fixes https://github.com/halo-dev/halo/issues/1921
Fixes https://github.com/halo-dev/halo/issues/1850

#### Screenshots:

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

2022-05-20 09:01 UTC, FanZeros commented
貌似这次PR把我上次改的内容也加进去了 #568

2022-05-20 10:55 UTC, guqing commented
> 貌似这次PR把我上次改的内容也加进去了 #568

可以通过如下方式优化一下commit

git fetch upstream
git reset --soft upstream/master
git add .
// check the changes
git commit -m "your message here"
git push origin HEAD -f

2022-05-20 11:38 UTC, FanZeros commented
> 

好的，按着流程做了一遍

2022-05-20 11:41 UTC, guqing requested changes

2022-05-20 11:41 UTC, guqing commented on .github/pull_request_template.md
> -<!--  Thanks for sending a pull request!  Here are some tips for you:
你不错误的删除了这个文件，需要撤销对该文件的更改

2022-05-20 11:50 UTC, guqing commented
你的commit message需要规范一下，我们代码审查通过后是bot自动合并，如果你的commit message不规范就需要我们手动干预才能合并，增加了工作量，建议你使用语义化的简短信息，使用英文概述此次提交所做的事情

2022-05-20 12:02 UTC, guqing commented
/retitle Remove leading and trailing spaces from the value of the URL type input elements

2022-05-20 12:07 UTC, FanZeros commented on .github/pull_request_template.md
> -<!--  Thanks for sending a pull request!  Here are some tips for you:
好的

2022-05-20 12:08 UTC, FanZeros commented
> 

懂了，麻烦你了

2022-05-24 11:15 UTC, JohnNiang reviewed
/cc @halo-dev/sig-halo-admin

2022-05-24 11:21 UTC, ruibaby commented
/cc @halo-dev/sig-halo-admin 

建议实际体验一下修改之后的输入体验。看看是否会对输入造成影响。个人认为最好的解决方式是添加表单验证规则，提示使用者不能包含前后空格，或者允许输入空格，但在提交的时候手动 trim 一下。

2022-05-24 15:28 UTC, FanZeros commented
> /cc @halo-dev/sig-halo-admin
> 
> 建议实际体验一下修改之后的输入体验。看看是否会对输入造成影响。个人认为最好的解决方式是添加表单验证规则，提示使用者不能包含前后空格，或者允许输入空格，但在提交的时候手动 trim 一下。

体验了下，目前没有发现会对输入造成影响。表单验证规则这一部分如果必要的话我最近会尝试一下相关实现。

2022-05-25 04:20 UTC, FanZeros commented
> > 体验了下，目前没有发现会对输入造成影响。表单验证规则这一部分如果必要的话我最近会尝试一下相关实现。
> 
> 主要考虑到使用者可能不明白为什么输入空格会没有反应，如果使用表单验证的话，可以比较直观的知道。

那些位置不应该包含空格的输入，感觉使用者不会特意去输入空格吧。不过你说的也很有道理

2022-07-12 15:09 UTC, JohnNiang commented
/ping @halo-dev/sig-halo-admin

2022-11-14 03:26 UTC, wzrove commented
> hi @FanZeros，你的commit message需要规范一下，我们代码审查通过后是bot自动合并，如果你的commit message不规范就需要我们手动干预才能合并，增加了工作量，建议你使用语义化的简短信息，使用英文概述此次提交所做的事情，你可以参考 halo 的历史提交信息来写 https://github.com/halo-dev/halo/commits/master

可以引入commitlint 配合 husky在本地提交前做校验。

2023-02-17 06:44 UTC, closed without merging