fix(): 🚸 提交表单 单独更新头像字段;
halo-dev/console pull request #619
Opened 2022-09-23 01:14 UTC by wxyShine

#### What type of PR is this?

#### What this PR does / why we need it:
/kind improvement
#### Which issue(s) this PR fixes:
Fixes #<2450>

#### Special notes for your reviewer:
ruibaby

#### Does this PR introduce a user-facing change?
之前: 修改头像 需要点击修改资料的保存按钮才可以保存新头像；
现在: 修改头像确定后直接保存新头像;

2022-09-23 01:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo-admin?pullRequest=619) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo-admin?pullRequest=619) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo-admin?pullRequest=619) it.</sub>

2022-09-23 02:56 UTC, ruibaby requested changes

2022-09-23 02:56 UTC, ruibaby commented on src/views/user/Profile.vue
> +          // 记录原始用户信息
这里没有必要去记录表单的数据，建议更新头像单独写逻辑即可。以下是 handleUpdateAvatar 这个方法的修改意见：

```js
// 获取用户信息
const {data} = await apiClient.user.getProfile()

data.avatar = updateAvatarForm.avatar

// 更新

await apiClient.user.updateProfile(data)

...
```

2022-09-23 02:56 UTC, ruibaby commented
@wxyShine 请先 Sign 一下我们的 CLA，https://github.com/halo-dev/halo-admin/pull/619#issuecomment-1255705332

2022-09-23 02:59 UTC, ruibaby commented
/retitle perf: update directly after selecting an avatar

2022-09-23 03:42 UTC, ruibaby reviewed
/lgtm

2022-09-23 03:42 UTC, guqing reviewed
/lgtm

2022-09-25 14:00 UTC, ruibaby reviewed
/approve

2022-09-25 14:02 UTC, ruibaby approved these changes

2022-09-25 14:02 UTC, merged

2022-10-05 05:25 UTC, JohnNiang commented
/milestone 1.6.x