feat: sort uploaded images
halo-dev/console pull request #631
Opened 2022-09-29 20:49 UTC by zjy4fun

#### What type of PR is this?

/kind optimization

#### What this PR does / why we need it:

优化后台图库批量添加图片的排序方式

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/2487

#### Screenshots:
![动画](https://user-images.githubusercontent.com/106857035/193135056-e49da8c8-26e9-4bc0-9b8b-e224d9b8e159.gif)

#### Special notes for your reviewer:

1. 添加了徽标用于展示添加图片的顺序，参考：https://1x.antdv.com/components/badge-cn/#API
2. 按照图片添加顺序进行排序

#### Does this PR introduce a user-facing change?

```release-note
所有页面-图库-选择附件界面添加了徽标，用于展示添加图片的顺序
```

2022-09-30 02:19 UTC, JohnNiang commented
/assign @halo-dev/sig-halo-console

2022-10-09 06:57 UTC, JohnNiang commented
/cc @halo-dev/sig-halo-console

2022-10-09 15:42 UTC, ruibaby requested changes

2022-10-09 15:42 UTC, ruibaby commented on src/components/Attachment/AttachmentSelectModal.vue
> +      attachment.selectedCount = this.list.selected.length
似乎没有必要去添加一个字段来记录序号。或许可以通过 `Array.prototype.indexOf` 来确定序号，毕竟这里的序号似乎只是用作显示。这个 PR 的改动主要逻辑是将选择图片的顺序倒序添加即可，那么我们在保存之前对 `handleAttachmentSelected` 的 `{ raw }` 数组进行倒序即可。

2022-10-10 03:29 UTC, zjy4fun commented on src/components/Attachment/AttachmentSelectModal.vue
> +      attachment.selectedCount = this.list.selected.length
感谢指点！那我先把这个pr关掉了

2022-10-10 03:32 UTC, ruibaby commented on src/components/Attachment/AttachmentSelectModal.vue
> +      attachment.selectedCount = this.list.selected.length
不用关闭，你可以修改之后直接在这个分支推送。

2022-10-10 03:45 UTC, guqing commented
/reopen 不用关闭，你可以修改之后直接在这个分支推送。

2022-10-10 05:22 UTC, zjy4fun commented
刚刚又提交了一下，使用索引展示序号更加方便（感谢@ruibaby）
如果不需要序号的话，也可以直接删除掉，这样看来我只需要加一个reverse就可以了 :joy_cat:

2022-10-10 07:36 UTC, ruibaby commented
> 如果不需要序号的话，也可以直接删除掉，这样看来我只需要加一个reverse就可以了 😹

我认为这个 PR 先不要添加这个序号好一点，因为这个 PR 的重点是修改添加到图库的顺序。而 `AttachmentSelectModal.vue` 这个组件在其他地方也有用到，也会同时修改了其他地方的表现。

2022-10-10 07:38 UTC, ruibaby commented
/retitle perf: batch add to photos in order of image selection

2022-10-10 07:38 UTC, ruibaby commented
/kind improvement
/milestone 1.6.x

2022-10-10 08:36 UTC, ruibaby reviewed
/approve

Cool!

2022-10-10 08:37 UTC, ruibaby commented
/cherrypick release-1.6

2022-10-10 08:38 UTC, guqing reviewed
/lgtm

2022-10-10 08:42 UTC, merged